version: "3.7"
services:
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
    - 5432:5432

  web:
    build: 
      context: .
      dockerfile: ./TimeCats.web/Dockerfile
    links: 
      - database
    depends_on: 
      - database
    command: dotnet run --urls=http://0.0.0.0:52082
    ports: 
      - "52082:52082"