version: "3.7"
services:
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - 5432:5432
  timecatsweb:
    build:
      context: ./TimeCats.web
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5555:80
    depends_on:
      - database