# This is the docker code that gets run when you use the command: docker-compose up
# it is used to build the containerized app. You will notice there is a database and web sections
# this is how we build both the database_1 and the web_1 portions of the app with the mentioned command.

version: "3.7"
services:
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
    - 5432:5432

  web:
    build: 
      context: .
      dockerfile: ./TimeCats.web/Dockerfile
    links: 
      - database
    depends_on: 
      - database
    command: dotnet run --urls=http://0.0.0.0:52082
    ports: 
      - "52082:52082"