// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TimeCats;

namespace TimeCats.Migrations
{
    [DbContext(typeof(TimeTrackerContext))]
    [Migration("20200806015210_NewTables")]
    partial class NewTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("TimeCats.Models.Course", b =>
                {
                    b.Property<int>("courseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("InstructorId")
                        .HasColumnType("integer");

                    b.Property<string>("courseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.HasKey("courseID");

                    b.HasIndex("InstructorId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            courseID = 1,
                            InstructorId = 2,
                            courseName = "Test Course",
                            description = "This is a test course for testing.",
                            isActive = true
                        });
                });

            modelBuilder.Entity("TimeCats.Models.Eval", b =>
                {
                    b.Property<int>("evalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("evalTemplateID")
                        .HasColumnType("integer");

                    b.Property<int>("groupID")
                        .HasColumnType("integer");

                    b.Property<bool>("isComplete")
                        .HasColumnType("boolean");

                    b.Property<int>("number")
                        .HasColumnType("integer");

                    b.Property<int>("userID")
                        .HasColumnType("integer");

                    b.HasKey("evalID");

                    b.ToTable("Evals");
                });

            modelBuilder.Entity("TimeCats.Models.EvalColumn", b =>
                {
                    b.Property<int>("originalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("evalID")
                        .HasColumnType("integer");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("originalID");

                    b.HasIndex("evalID");

                    b.ToTable("EvalColumn");
                });

            modelBuilder.Entity("TimeCats.Models.EvalResponse", b =>
                {
                    b.Property<int>("evalResponseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("categoryName")
                        .HasColumnType("text");

                    b.Property<int>("columTotal")
                        .HasColumnType("integer");

                    b.Property<int>("evalID")
                        .HasColumnType("integer");

                    b.Property<int>("evalNumber")
                        .HasColumnType("integer");

                    b.Property<int>("evalTemplateQuestionID")
                        .HasColumnType("integer");

                    b.Property<string>("firstName")
                        .HasColumnType("text");

                    b.Property<string>("lastName")
                        .HasColumnType("text");

                    b.Property<int>("questionNumber")
                        .HasColumnType("integer");

                    b.Property<string>("questionText")
                        .HasColumnType("text");

                    b.Property<string>("response")
                        .HasColumnType("text");

                    b.Property<double>("userAvgerage")
                        .HasColumnType("double precision");

                    b.Property<int>("userID")
                        .HasColumnType("integer");

                    b.HasKey("evalResponseID");

                    b.HasIndex("evalID");

                    b.ToTable("EvalResponses");
                });

            modelBuilder.Entity("TimeCats.Models.EvalTemplate", b =>
                {
                    b.Property<int>("evalTemplateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("inUse")
                        .HasColumnType("boolean");

                    b.Property<string>("templateName")
                        .HasColumnType("text");

                    b.Property<int>("userID")
                        .HasColumnType("integer");

                    b.HasKey("evalTemplateID");

                    b.ToTable("EvalTemplates");
                });

            modelBuilder.Entity("TimeCats.Models.EvalTemplateQuestion", b =>
                {
                    b.Property<int>("evalTemplateQuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("evalID")
                        .HasColumnType("integer");

                    b.Property<int>("evalTemplateID")
                        .HasColumnType("integer");

                    b.Property<int>("evalTemplateQuestionCategoryID")
                        .HasColumnType("integer");

                    b.Property<int>("number")
                        .HasColumnType("integer");

                    b.Property<string>("questionText")
                        .HasColumnType("text");

                    b.Property<char>("questionType")
                        .HasColumnType("character(1)");

                    b.HasKey("evalTemplateQuestionID");

                    b.HasIndex("evalID");

                    b.HasIndex("evalTemplateID");

                    b.ToTable("EvalTemplateQuestions");
                });

            modelBuilder.Entity("TimeCats.Models.EvalTemplateQuestionCategory", b =>
                {
                    b.Property<int>("evalTemplateQuestionCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("categoryName")
                        .HasColumnType("text");

                    b.Property<int?>("evalID")
                        .HasColumnType("integer");

                    b.Property<int>("evalTemplateID")
                        .HasColumnType("integer");

                    b.Property<int>("number")
                        .HasColumnType("integer");

                    b.HasKey("evalTemplateQuestionCategoryID");

                    b.HasIndex("evalID");

                    b.HasIndex("evalTemplateID");

                    b.ToTable("EvalTemplateQuestionCategories");
                });

            modelBuilder.Entity("TimeCats.Models.Group", b =>
                {
                    b.Property<int>("groupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("groupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<int>("projectID")
                        .HasColumnType("integer");

                    b.HasKey("groupID");

                    b.HasIndex("projectID");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            groupID = 1,
                            groupName = "Test Group 1",
                            isActive = true,
                            projectID = 1
                        });
                });

            modelBuilder.Entity("TimeCats.Models.Project", b =>
                {
                    b.Property<int>("projectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CourseID")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<string>("projectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("projectID");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            projectID = 1,
                            CourseID = 1,
                            description = "This is the first test project",
                            isActive = true,
                            projectName = "Test Project 1"
                        });
                });

            modelBuilder.Entity("TimeCats.Models.TimeCard", b =>
                {
                    b.Property<int>("timeslotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("groupID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("timeIn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("timeOut")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("userID")
                        .HasColumnType("integer");

                    b.HasKey("timeslotID");

                    b.HasIndex("groupID");

                    b.HasIndex("userID");

                    b.ToTable("TimeCards");
                });

            modelBuilder.Entity("TimeCats.Models.User", b =>
                {
                    b.Property<int>("userID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int?>("evalID")
                        .HasColumnType("integer");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<char>("type")
                        .HasColumnType("character(1)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("userID");

                    b.HasIndex("evalID");

                    b.HasIndex("username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            userID = 1,
                            Salt = new byte[] { 241, 38, 81, 111, 31, 219, 233, 186, 205, 191, 121, 36, 126, 161, 230, 253, 79, 177, 217, 255, 214, 152, 234, 249, 240, 204, 191, 148, 122, 246, 61, 146 },
                            firstName = "Adam",
                            isActive = true,
                            lastName = "Admin",
                            password = "JSPeE8IaVUr/ldys5W5lbfOCA4neeb6vUEwnw+X48Y8=",
                            type = 'A',
                            username = "Admin"
                        },
                        new
                        {
                            userID = 2,
                            Salt = new byte[] { 241, 38, 81, 111, 31, 219, 233, 186, 205, 191, 121, 36, 126, 161, 230, 253, 79, 177, 217, 255, 214, 152, 234, 249, 240, 204, 191, 148, 122, 246, 61, 146 },
                            firstName = "Steve",
                            isActive = true,
                            lastName = "Jobs",
                            password = "JSPeE8IaVUr/ldys5W5lbfOCA4neeb6vUEwnw+X48Y8=",
                            type = 'I',
                            username = "Instructor"
                        },
                        new
                        {
                            userID = 3,
                            Salt = new byte[] { 241, 38, 81, 111, 31, 219, 233, 186, 205, 191, 121, 36, 126, 161, 230, 253, 79, 177, 217, 255, 214, 152, 234, 249, 240, 204, 191, 148, 122, 246, 61, 146 },
                            firstName = "Normal",
                            isActive = true,
                            lastName = "User",
                            password = "JSPeE8IaVUr/ldys5W5lbfOCA4neeb6vUEwnw+X48Y8=",
                            type = 'S',
                            username = "User"
                        });
                });

            modelBuilder.Entity("TimeCats.Models.UserCourse", b =>
                {
                    b.Property<int>("userID")
                        .HasColumnType("integer");

                    b.Property<int>("courseID")
                        .HasColumnType("integer");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.HasKey("userID", "courseID");

                    b.HasIndex("courseID");

                    b.ToTable("UserCourses");

                    b.HasData(
                        new
                        {
                            userID = 3,
                            courseID = 1,
                            isActive = false
                        });
                });

            modelBuilder.Entity("TimeCats.Models.UserGroup", b =>
                {
                    b.Property<int>("userID")
                        .HasColumnType("integer");

                    b.Property<int>("groupID")
                        .HasColumnType("integer");

                    b.HasKey("userID", "groupID");

                    b.HasIndex("groupID");

                    b.ToTable("UserGroups");

                    b.HasData(
                        new
                        {
                            userID = 3,
                            groupID = 1
                        });
                });

            modelBuilder.Entity("TimeCats.Models.Course", b =>
                {
                    b.HasOne("TimeCats.Models.User", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TimeCats.Models.EvalColumn", b =>
                {
                    b.HasOne("TimeCats.Models.Eval", null)
                        .WithMany("evals")
                        .HasForeignKey("evalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TimeCats.Models.EvalResponse", b =>
                {
                    b.HasOne("TimeCats.Models.Eval", null)
                        .WithMany("responses")
                        .HasForeignKey("evalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TimeCats.Models.EvalTemplateQuestion", b =>
                {
                    b.HasOne("TimeCats.Models.Eval", null)
                        .WithMany("templateQuestions")
                        .HasForeignKey("evalID");

                    b.HasOne("TimeCats.Models.EvalTemplate", null)
                        .WithMany("templateQuestions")
                        .HasForeignKey("evalTemplateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TimeCats.Models.EvalTemplateQuestionCategory", b =>
                {
                    b.HasOne("TimeCats.Models.Eval", null)
                        .WithMany("categories")
                        .HasForeignKey("evalID");

                    b.HasOne("TimeCats.Models.EvalTemplate", null)
                        .WithMany("categories")
                        .HasForeignKey("evalTemplateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TimeCats.Models.Group", b =>
                {
                    b.HasOne("TimeCats.Models.Project", "Project")
                        .WithMany("groups")
                        .HasForeignKey("projectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TimeCats.Models.TimeCard", b =>
                {
                    b.HasOne("TimeCats.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("groupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeCats.Models.User", "User")
                        .WithMany("timecards")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TimeCats.Models.User", b =>
                {
                    b.HasOne("TimeCats.Models.Eval", null)
                        .WithMany("users")
                        .HasForeignKey("evalID");
                });

            modelBuilder.Entity("TimeCats.Models.UserCourse", b =>
                {
                    b.HasOne("TimeCats.Models.Course", "Course")
                        .WithMany("UserCourses")
                        .HasForeignKey("courseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeCats.Models.User", "User")
                        .WithMany("UserCourses")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TimeCats.Models.UserGroup", b =>
                {
                    b.HasOne("TimeCats.Models.Group", "Group")
                        .WithMany("UserGroups")
                        .HasForeignKey("groupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeCats.Models.User", "User")
                        .WithMany("UserGroups")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
